# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ByRa
                                 A QGIS plugin
 This tool yadda adda yadda
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-04-24
        copyright            : (C) 2018 by ByRA
        email                : maxczapanskiy@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ByRa class from file ByRa.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .byra import ByRa
    return ByRa(iface)
